name: wheretosleepincsu
description: A new Flutter project.

version: 0.92+16

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  image_picker: ^0.6.5
  flutter_bugly: ^0.2.6
  package_info: ^0.4.0+16
  path_provider: ^1.6.5
  barcode_scan: ^3.0.1
  url_launcher: ^5.4.2
  scoped_model: ^1.0.1
  fluttertoast: ^4.0.1
  qr_flutter: ^3.2.0
  sqflite: ^1.3.0
  intl_utils: ^1.6.2

  html:
    git:
      url: git://github.com/chen-zeyu/html.git
      ref: patch-pola
#  text_view:
#    git:
#      url: git://github.com/felangel/flutter_text_view_plugin.git
#  html: ^0.14.0+2
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon.png
flutter_intl:
  enabled: true
